name = "GeoSpatialRelations"
uuid = "9c2cbfb9-3811-41fb-8b11-4506ae95e66c"
authors = ["adribrune <adrianb.brune@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.15"
